# The name of the environment 
name: extraINSIGHT
# The relevent channels
channels:
- conda-forge
- bioconda
#  Python dependencies
dependencies:
- python=3.7
- pandas
- numpy
- scipy
- snakemake-minimal
- r-base=3.6.1
- r-stringi
- r-data.table
- r-gtools
- r-argparse
- bioconductor-sgseq
- bioconductor-rtracklayer
- bioconductor-genomicfeatures
- bioconductor-txdb.hsapiens.ucsc.hg38.knowngene
- bioconductor-genomicranges
- bedops
- bedtools
- pyyaml
- ucsc-liftover
- emacs
