# The name of the environment 
name: extraINSIGHT
# The relevent channels
channels:
- conda-forge
- bioconda
#  Python dependencies
dependencies:
- python=3.7
- pandas
- numpy
- scipy
- snakemake-minimal
- pyyaml
- r-base=4.0.0
- r-stringi
- r-stringr
- r-data.table
- r-gtools
- r-argparse
- r-ggplot2
- r-cowplot
- r-processx
- r-ggrepel
- r-r.utils
- bioconductor-sgseq
- bioconductor-rtracklayer
- bioconductor-iranges
- bioconductor-genomicfeatures
- bioconductor-genomicranges
- bioconductor-genomeinfodb
- bioconductor-ensembldb
- bioconductor-annotationhub
- bedops
- bedtools
- ucsc-liftover
- emacs
